### ISSUE TITLE
unpassed verification against cublas sgemm

### ISSUE THREAD

**Issue by gillbam** [yzhaiustc/Optimizing-SGEMM-on-NVIDIA-Turing-GPUs#2]
hello,

thanks for your great work! I found when I have unsquared inputs, e.g. M = 35, N = 79, K= 19, tests of all kernels are failed. Do you have any idea about this issue?

best regards

**Comment by yzhaiustc** [comment]
Thanks for the interests.
Most of the kernels are for demonstration purpose such that they require some of input dimensions divisible by their corresponding blocking sizes. This explains why those inputs not multipliers of 8 or 32 cannot pass test cases.

**Comment by gillbam** [comment]
Thanks for your reply
