### ISSUE TITLE
Reducing bank conflictions error in kernel 4

### ISSUE THREAD

**Issue by theoqian** [yzhaiustc/Optimizing-SGEMM-on-NVIDIA-Turing-GPUs#3]
Hi, the shared memory in kernel 4 is column major according to line 6 and 7. But line 27 accesses 'sb4' by 'row' (which is consecutive of thread id) on 2nd dimension. That means consecutive threads still access scattered shared memory.
The speed of this code on my RTX 2080ti is:
```
M=N=K=256:
Average elasped time: 0.000049 second, performance: 679.173522 GFLOPS.

M=N=K=512:
Average elasped time: 0.000324 second, performance: 828.578150 GFLOPS.

M=N=K=768:
Average elasped time: 0.001080 second, performance: 838.995059 GFLOPS.

M=N=K=1024:
Average elasped time: 0.002519 second, performance: 852.364426 GFLOPS.

M=N=K=1280:
Average elasped time: 0.004891 second, performance: 857.639395 GFLOPS.

M=N=K=1536:
Average elasped time: 0.007778 second, performance: 931.870010 GFLOPS.

M=N=K=1792:
Average elasped time: 0.010060 second, performance: 1144.078582 GFLOPS.

M=N=K=2048:
Average elasped time: 0.014952 second, performance: 1148.978555 GFLOPS.
```

The speed above is even slower than naive implementation of kernel 1 without using shared memory.
I tried to solve the bank conflictions by accessing 'sb4' using consecutive threads 'row' on 1st dimension like this:
```
sa4(row,col)=A(row,col);
sb4(row,col)=B(row,col);
A+=(lda<<5);B+=32;
__syncthreads();
for (int inner_k_count=0;inner_k_count<KS;inner_k_count++){
    tmp += sa4(row,inner_k_count) * sb4(inner_k_count,col);
}
```
The speed was improved as below and it's faster than naive kernel 1:
```
M=N=K=256:
Average elasped time: 0.000031 second, performance: 1072.821737 GFLOPS.

M=N=K=512:
Average elasped time: 0.000183 second, performance: 1463.878317 GFLOPS.

M=N=K=768:
Average elasped time: 0.000608 second, performance: 1489.360494 GFLOPS.

M=N=K=1024:
Average elasped time: 0.001381 second, performance: 1554.788349 GFLOPS.

M=N=K=1280:
Average elasped time: 0.002745 second, performance: 1528.041037 GFLOPS.

M=N=K=1536:
Average elasped time: 0.004654 second, performance: 1557.176527 GFLOPS.

M=N=K=1792:
Average elasped time: 0.007357 second, performance: 1564.402972 GFLOPS.

M=N=K=2048:
Average elasped time: 0.009352 second, performance: 1836.994741 GFLOPS.
```

**Comment by yzhaiustc** [comment]
Thank you very much for the suggestion!
Yes, this is indeed a great point.
In kernel5, if to change the loop code snippet following your suggestion to: 
```
    for (int k_count = 0; k_count<K; k_count+=KS){
        sa5(row1,col)=A(row1,col);
        sa5(row2,col)=A(row2,col);
        sa5(row3,col)=A(row3,col);
        sa5(row4,col)=A(row4,col);
        sb5(row1, col)=B(row1,col);
        sb5(row2, col)=B(row2,col);
        sb5(row3, col)=B(row3,col);
        sb5(row4, col)=B(row4,col);
        A+=(lda<<5);B+=32;
        __syncthreads();
        #pragma unroll
        for (int inner_k_count=0;inner_k_count<KS;inner_k_count++){
            b00 = sb5(inner_k_count, col);
            Cres[0] += sa5(row1,inner_k_count) * b00;
            Cres[1] += sa5(row2,inner_k_count) * b00;
            Cres[2] += sa5(row3,inner_k_count) * b00;
            Cres[3] += sa5(row4,inner_k_count) * b00;
        }
        __syncthreads();
    }
```
one can also observe an acceleration compared to the current kernel5.
However, the reason why I made kernel4 in this under-optimized implementation is actually for the sake of being consistent with vectorized kernels, such that we can better observe the impact of introducing SIMD LD/ST.
As you can see in kernel5, each thread copies 4 elements for both A & B into shared memory. In this version (kernel5), the memory access pattern of B_copy is mostly the same as that in kernel4, but with {one B element copy per thread extended to 4 consecutive B element copies per thread}. 
In kernel6, I changed mostly nothing compared to kernel5, in regards to the memory access pattern, but just introduced vectorized LD/ST for both A and B. 
**That being said, all the performance gain from kernel5 to kernel6 will thus be purely due to introducing vectorized LD/ST. I believe this will help to better demonstrate the ideas of more complicated kernels.**

Thank you again for your valuable input! I really appreciate it.
Please just let me know about any further suggestions or opinions :)

**Comment by yzhaiustc** [comment]
Following up the previous message, ```nvcc``` generates SIMD store for the code snippet 
```
        ((float4 *)sa6)[tx] = Av;
        sb6(col,row1)=Bv.x;
        sb6(col,row2)=Bv.y;
        sb6(col,row3)=Bv.z;
        sb6(col,row4)=Bv.w;
```
since the compiler detects that 128-bit vectorized data are stored to 4 consecutive addresses.

**Comment by theoqian** [comment]
Thanks for your reply. For kernel6, I think we can also remove shared memory bank conflicts from it. We just need to make sb6 column major just like global matrix B. Then we can use vectorized LD/ST directly by '((float4 *)sb6)[tx] = Bv;' (which doesn't even need explicit unpack since sb6 and B are both column major). I'm not familiar with vectorized LD/ST so maybe I ignored some factors. Or maybe you organize the memory like this to control some factors and compare with kernel7 etc. Anyway thanks for discussing it with me and really willing to learn more from you.
```
#define sb6(i,j) sb6[((j)<<5) + (i)]
for (int k_count = 0; k_count<K; k_count+=KS){
        Av = *((float4 *)(&A(row1,col)));
        Bv = *((float4 *)(&B(row1,col)));
        ((float4 *)sa6)[tx] = Av;
        ((float4 *)sb6)[tx] = Bv;
        //sb6(col,row1)=Bv.x;
        //sb6(col,row2)=Bv.y;
        //sb6(col,row3)=Bv.z;
        //sb6(col,row4)=Bv.w;
        A+=(lda<<5);B+=32;
        __syncthreads();
        #pragma unroll
        for (int inner_k_count=0;inner_k_count<KS;inner_k_count++){
            b00 = sb6(inner_k_count,col);
            Cres.x += sa6(row1,inner_k_count) * b00;
            Cres.y += sa6(row2,inner_k_count) * b00;
            Cres.z += sa6(row3,inner_k_count) * b00;
            Cres.w += sa6(row4,inner_k_count) * b00;
        }
        __syncthreads();
    }
```

**Comment by yzhaiustc** [comment]
Oh gosh. Thank you very much!
This is a typo --- the col major/row major issue of ```sb6``` in kernel6.
I'll fix it and update the performance plot soon.
If you found any other issues or anything you would like to discuss, please don't hesitate to reach out to me.
Thank you again for your insightful input :)

**Comment by yzhaiustc** [comment]
Thank you for the insightful input!
This was a typo. I have updated the code snippet to:
```
#define sb6(i,j) sb6[((j)<<5) + (i)]
    for (int k_count = 0; k_count<K; k_count+=KS){
        Av = *((float4 *)(&A(row1,col)));
        Bv = *((float4 *)(&B(row1,col)));
        ((float4 *)sa6)[tx] = Av;
        sb6(col,row1)=Bv.x;
        sb6(col,row2)=Bv.y;
        sb6(col,row3)=Bv.z;
        sb6(col,row4)=Bv.w;
        A+=(lda<<5);B+=32;
        __syncthreads();
        #pragma unroll
        for (int inner_k_count=0;inner_k_count<KS;inner_k_count++){
            b00 = sb6(col, inner_k_count);
            Cres.x += sa6(row1,inner_k_count) * b00;
            Cres.y += sa6(row2,inner_k_count) * b00;
            Cres.z += sa6(row3,inner_k_count) * b00;
            Cres.w += sa6(row4,inner_k_count) * b00;
        }
        __syncthreads();
    }
```
and the perf plot will be updated accordingly.

This is slightly slower than the version that you have suggested. However, I believe this would be more consistent with following kernels in terms of the memory access pattern, where we load data from ```b buffer``` in a vectorized manner. In these kernels, we transpose B elements when moving them into the shared memory such that we can load them in a vectorized manner from shared memory in the ```inner_k loop``` for computing.

I wrote these kernels down around last Oct so it's been a bit difficult that I can pick up all the details.
But it would be definitely nice that the open-source community can help to polish this project :)
Thank you very much again for your great efforts and interests. I am looking forward to any further suggestions or comments from you.
